defaults:
  - bigpipe
  - bigpipe_override

django:
  port: 8080
  params:
    - runserver
    - 0.0.0.0:${django.port}

demo:
  view_wait_from: 1
  view_wait_to: 10
  title_minimum_word_count: 3
  content_minimum_word_count: 15

hydra:
  run:
    dir: .