bigpipe:
  rendered_output_path: ${full_path:public}
  static_uri: 'public'
  is_production_mode: false

  processors:
    js:
      source_path:
        - ${full_path:client}
    css:
      source_path:
        - ${full_path:client}